magpie.address: http://172.22.178.85:8080/magpie-conf-service/conf/
online.address: https://raw.githubusercontent.com/hackerwin7/configuration-service/master/
offline.address: http://train.bdp.jd.com/api/ztc/job/getJobConfig.ajax?jobId=