magpie.address: http://172.22.178.85:8080/magpie-conf-service/conf/
online.address: https://raw.githubusercontent.com/hackerwin7/configuration-service/master/mysql-tracker-json
offline.address: http://192.168.144.98:8000/api/ztc/job/getJobConfig.ajax?jobId=